### ISSUE TITLE
Set up automatic build and deployment

### ISSUE THREAD

**Issue by ezamriy** [AlmaLinux/wiki#1]
It would be nice to build static content and push it to the `gh-pages` automatically instead of calling `deploy.sh` all the time.

There are many solutions for this:

- [Travis CI](https://travis-ci.org/) integration as described [here](https://vuepress.vuejs.org/guide/deploy.html#github-pages-and-travis-ci)
- [Vuepress deploy](https://github.com/marketplace/actions/vuepress-deploy) GitHub action
- Create a pipeline in our internal Jenkins

**Comment by Addvilz** [comment]
@ezamriy might not be the best idea to use TravisCI.org, since it is shutting down and migrating to TravisCI.com - which only grants so many credits for free, and you need to be validated to get more.

**Comment by jaboutboul** [comment]
probably best to do this via a gh action

**Comment by jaboutboul** [comment]
@andrewlukoshko do we have any update on this?

**Comment by andrewlukoshko** [comment]
Yes. It's resolved :)
