### ISSUE TITLE
AlmaLinux 9 support period

### ISSUE THREAD

**Issue by rossengeorgiev** [AlmaLinux/wiki#222]
Hi, 
looking at the FAQ page the support of AlmaLinux is listed as until 2029, and links to AlmaLinux 8 announcement.  

* Does that apply to both AL 7 & 8? 
* Or does the FAQ page need to be updated?
* Is there a better source of support commitment information? 

https://github.com/AlmaLinux/wiki/blob/d422478d1bc7568b64b2aaede0c07f2472bca16a/docs/FAQ.md?plain=1#L73-L77

**Comment by andrewlukoshko** [comment]
Nice catch. AlmaLinux 9 will be supported until 2032.
We'll update this answer.

**Comment by rossengeorgiev** [comment]
Awesome. Thanks for the link
