### ISSUE TITLE
SSL Certificate issue - https://chat.almalinux.org

### ISSUE THREAD

**Issue by huangsen365** [AlmaLinux/wiki#224]
SSL Certificate issue - https://chat.almalinux.org

**Comment by huangsen365** [comment]
![image](https://user-images.githubusercontent.com/1982355/215310451-254c58a4-c332-4dc3-9d9f-883eaa82a188.png)

**Comment by huangsen365** [comment]
![image](https://user-images.githubusercontent.com/1982355/215310477-3a61c55d-f97c-48a7-9a0f-457fd8d9c5ad.png)

**Comment by andrewlukoshko** [comment]
Fixed. Thanks.
