### ISSUE TITLE
Clarification about Oracle binary compat from comparision page

### ISSUE THREAD

**Issue by rossengeorgiev** [AlmaLinux/wiki#236]
Hi,
I was looking at the comparison page. Oracle Enterprise Linux is listed as `Almost*(some divergance in glibc, openssl and other components)`, but there is reference to source of that information. I'm interested in understanding what the divergence is, and would be very grateful to be pointed toward more information related to it.

Wiki page:
https://github.com/AlmaLinux/wiki/blame/e2d44bb5a347795c1be2f9418db57e5785371f90/docs/Comparison.md#L8

From the OEL release post they claim 100% app compat:

```
Oracle Linux is a highly performant and secure operating environment that helps accelerate digital transformation. It is supported across hybrid and multicloud deployments. Oracle Linux is 100% application binary compatible with Red Hat Enterprise Linux. [Existing applications](https://www.oracle.com/linux/isvcatalog) in user space will continue to run unmodified on Oracle Linux 8 update 6 with [Unbreakable Enterprise Kernel Release 6 (UEK R6)](https://blogs.oracle.com/linux/announcing-the-unbreakable-enterprise-kernel-release-6-update-2-for-oracle-linux) and applications already certified on previous releases of Red Hat Enterprise Linux 8 or Oracle Linux 8 do not require a certification with this new release.
```

Thanks

**Comment by bennyvasquez** [comment]
This was resolved in #256, so closing. If there's still a problem, feel free to reopen or open a new issue.
