### ISSUE TITLE
IRC Network change from Freenode to Libera

### ISSUE THREAD

**Issue by bittin** [AlmaLinux/wiki#30]
Hello!

Watching your talk at the OpenSUSE Conference Online 2021 on Youtube now: https://youtu.be/mX5XRI_l-1M?list=PL_AMhvchzBafs77OghDUqlDwrIBl9R5QW 

And noticed you might want to change the IRC channel link on the wiki: https://wiki.almalinux.org/ from Freenode to Libera

**Comment by jaboutboul** [comment]
Thanks. Very funny. I am actually working on a load of wiki edits as we speak!
