### ISSUE TITLE
Azure marketplace link to official image is broken

### ISSUE THREAD

**Issue by cmd-ntrf** [AlmaLinux/wiki#312]
The following link is broken:
https://github.com/AlmaLinux/wiki/blob/853137cbd73a65f618ee90afbd3d7391736498e9/docs/cloud/Azure.md?plain=1#L25

Should it be this : https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux-x86_64?tab=Overview ?

**Comment by codyro** [comment]
Nice catch! We can either link to the `x86_64` image directly, or the search page which will show the images for `HPC`, `x86_64`, and `arm64`. 

`https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=AlmaLinux`

**Comment by bennyvasquez** [comment]
Since we can't link directly to the image in question, I'd say a search for all AlmaLinux options would be better, yeah. Good catch @cmd-ntrf and @codyro!

**Comment by andrewlukoshko** [comment]
Search link shows a lot of unofficial 3rd party offers.
I'd better prefer to mention all available images but directly.

**Comment by codyro** [comment]
I concur. I will update it accordingly.
