### ISSUE TITLE
Document ELevate migration for disconnected environments

### ISSUE THREAD

**Issue by andrewlukoshko** [AlmaLinux/wiki#344]
It's an often situation when nodes don't have direct Internet access and rely on local mirror for receiving updates.
We need to document migration for such scenarios.
It may be called **ELevate Offline Guide** or something like that and contain the following information:
1. Creating of AlmaLinux mirror - based on steps 1-3 from https://wiki.almalinux.org/Mirrors.html
2. Creating of ELevate mirror - pretty the same but rsync URL is rsync://rsync.repo.almalinux.org/almalinux-elevate/
3. Adding local ELevate mirror to server (repo file)
4. Installing ELevate
5. Updating leapp configuration (basically replacing mirror server URLs with local mirror URLs)
6. Perform migration

**Comment by bennyvasquez** [comment]
Love this! I've also seen this called an "airgapped environment", so it'll be worth using that word in our descriptions as well, for search-ability purposes.

**Comment by sboldyreva** [comment]
The guide was published
https://github.com/AlmaLinux/wiki/pull/355

**Comment by dummys** [comment]
hello just to add that for me it was impossible to do it with `file:///myrepo` as it does not mounted inside the systemd-nspawn, I have to use a local `python -m http.server` to make it work and use `http://localhost/myrepo`

**Comment by bennyvasquez** [comment]
@dummys please open an issue on this repo with more details - we don't typically monitor old issues.
