### ISSUE TITLE
Add a separate page how to get assistance 

### ISSUE THREAD

**Issue by sboldyreva** [AlmaLinux/wiki#362]
Currently, it's unclear how users can get any assistance. Having a separate page dedicated to this that is easy to spot for users could be a good idea. For everyone's convenience, it may be worth mentioning all the discussion spaces and some recommendations.

Also may help with the https://github.com/AlmaLinux/wiki/issues/341

The pr to collaborate - https://github.com/AlmaLinux/wiki/pull/361

**Comment by codyro** [comment]
Looks fantastic to me. Thank you for doing this :)

**Comment by sboldyreva** [comment]
closing this issue as #361 got merged
