### ISSUE TITLE
Enumeration error in "Contributing to the AlmaLinux project" doc

### ISSUE THREAD

**Issue by Lab-Brat** [AlmaLinux/wiki#391]
Hello everyone 🙂 

While browsing through [Contributing to the AlmaLinux project documentation](https://github.com/AlmaLinux/wiki/blob/master/docs/Contribute.md#contributing-to-the-almalinux-project) page, I noticed the number "**3**" is missing in the [Specific Areas we need help with](https://github.com/AlmaLinux/wiki/blob/master/docs/Contribute.md#specific-areas-we-need-help-with) section.

Enumeration goes like this: 1, 2, 4, 5, 6. I think it was changed in https://github.com/AlmaLinux/wiki/commit/869a67fe02b364ce96d41dd6c9fe00e1db640f65

**Comment by bennyvasquez** [comment]
Ah! Good catch! Do you have interest in submitting a pull request to fix it? No worries if not! One of us will get it fixed soon, either way.

**Comment by Lab-Brat** [comment]
PR submitted! (https://github.com/AlmaLinux/wiki/pull/394)

**Comment by bennyvasquez** [comment]
Thanks for the PR!
