### ISSUE TITLE
update discourse links 

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/wiki#407]
With the migration from almalinux.discourse.group to forums.almalinux.org, the links need to be updated.

**Comment by Noam-Alum** [comment]
I updated the links on the wiki, here is the [PR](https://github.com/AlmaLinux/wiki/pull/408).

**Comment by Noam-Alum** [comment]
Here is the new [PR](https://github.com/AlmaLinux/wiki/pull/409), let me know now its good.

**Comment by Noam-Alum** [comment]
I think we can close this issue, Jonathan merged my branch.
