### ISSUE TITLE
Adjust navigation - release notes

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/wiki#423]
I think the menu list of releases is getting quite difficult to navigate and won't scale further without usability problems. I also don't think it belongs under 'documentation' as it's not really part of what else is there, and it seems like we're burying the release notes quite a bit. I'd like to suggest a solution. 

How it is now: 
![2024-05-27_17-41-56](https://github.com/AlmaLinux/wiki/assets/13630986/86ac57ae-69e0-4c61-bc83-424efcf31994)

I think we should leave the most recent versions easily accessible, but group the older version 8 and version 9 release notes together, and then within those group the betas together. I also think the release notes should also be a top-level menu item, just under the home page. Like this:

![2024-05-27_19-05-28](https://github.com/AlmaLinux/wiki/assets/13630986/242da0ff-4ca8-4eec-8351-beb18855bcbc)

**Comment by bennyvasquez** [comment]
> What about instead of "Older AlmaLinux 9 beta releases" it's just "beta releases" (keeping individual "beta releases" sections under 8/9 respectively)

Oh, I like that! Adjusted the PR to reflect that.

**Comment by bennyvasquez** [comment]
Also looking for @sboldyreva and @andrewlukoshko's eyes on this. Love to hear what y'all think!

**Comment by codyro** [comment]
This makes it look much clearer and cleaner to me.

**Comment by sboldyreva** [comment]
For sure clearing up the menu is a must! 
As we have the 10 coming soon, I was actually thinking about this kind of subsections:
![image](https://github.com/AlmaLinux/wiki/assets/87830789/5bfc3239-06ef-42b3-a19f-079e3028fe7b)

**Comment by bennyvasquez** [comment]
Super similar to what I was thinking! For me, I like the idea of making the most recent releases immediately accessible and moving the older ones to a folder. The likelihood is that folks will be looking for the most recent ones much more regularly than the older ones, so we're saving clicks for most people.
