### ISSUE TITLE
Update guides with new CentOS 7 infomation

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/wiki#451]
As an extension of #449, these two ELevate guides need to be tested and updated, now that CentOS 7's repos are offline. 

docs/elevate/ELevate-offline-guide.md
docs/elevate/ELevating-CentOS6-to-CentOS7.md

**Comment by bennyvasquez** [comment]
@sboldyreva created this issue so it doesn't get lost.

**Comment by sboldyreva** [comment]
@bennyvasquez the ELevate offline guide seem to not require any updates. 
The ELevate CentOS 6 to CentOS 7 guide was updated: https://github.com/AlmaLinux/wiki/pull/452

**Comment by bennyvasquez** [comment]
You’re the BEST. Thanks for finding time for this before your vaca. <3
