### ISSUE TITLE
Instructions to write an image on a USB using dd are missing a final sync

### ISSUE THREAD

**Issue by FilipeMaia** [AlmaLinux/wiki#469]
The instructions for using the iso files into a USB using `dd` shown in https://wiki.almalinux.org/documentation/installation-guide.html#write-an-image-on-a-usb use:
`sudo dd if=./AlmaLinux-9.1-x86_64-dvd.iso of=/dev/sdX status=progress`

This risks ending up with a partially written image if the user removes the USB device immediately after the command returns, as the writes may be cached.

I suggest changing it to:
`sudo dd if=./AlmaLinux-9.1-x86_64-dvd.iso of=/dev/sdX status=progress && sync` 
or
`sudo dd if=./AlmaLinux-9.1-x86_64-dvd.iso of=/dev/sdX status=progress conv=fsync`

**Comment by jonathanspw** [comment]
Good catch!  Would you like to PR a fix?

**Comment by FilipeMaia** [comment]
Sure!

**Comment by codyro** [comment]
It might be worth specifying a block size for these commands (IIRC default is 512 bytes) as well.

**Comment by FilipeMaia** [comment]
Fair point. I added `bs=4M`.

**Comment by bennyvasquez** [comment]
Thank you so much!
