### ISSUE TITLE
`rsync` copies unneeded source UID/GIDs when mirroring

### ISSUE THREAD

**Issue by syu5488** [AlmaLinux/wiki#542]
The wiki advises those wanting to mirror the RPM repositories to use the `-a` option when running `rsync` (example: [link]), but this option preserves source UID/GIDs unneeded by the receiver. For example:
```
# rsync -a rsync://rsync.repo.almalinux.org/almalinux/robots.txt .
# ls -l robots.txt
-rw-r--r--. 1 10568 10568 26 May 31  2024 robots.txt
# id 10568
id: ‘10568’: no such user
```
At best, it's harmless. At worst, it collides with another user. To prevent any surprises and make requirements more explicit, how about *not* preserving these two attributes by changing from `-a` to `-rlpt`?

Note: the existing `-a` option actually implies further options — the full thing being: `-rlptgoD`. Other than `-g` and `-o` for preserving group and owner, the `-D` option tells `rsync` to transfer character devices, block devices, named sockets, and named pipes. None of these apply here as far as I understand which is why I excluded `-D` as well.

[link]: https://github.com/AlmaLinux/wiki/blob/1a9f9ae8ac6742baf88a42091ff25c8b945de4d5/docs/Mirrors.md?plain=1#L32

**Comment by bennyvasquez** [comment]
Thanks for the report! Since this is mirror-specific, I'm tagging in @AlmaLinux/infrastructure-sig.

**Comment by codyro** [comment]
Makes sense to me.

```shell
[root@b730018c3708 ~]# rsync -a rsync://rsync.repo.almalinux.org/almalinux/robots.txt .
[root@b730018c3708 ~]# ls -lh
total 4.0K
-rw-r--r-- 1 10568 10568 26 May 31  2024 robots.txt
[root@b730018c3708 ~]# rsync -rlpt rsync://rsync.repo.almalinux.org/almalinux/robots.txt ./robots2.txt
[root@b730018c3708 ~]# ls -lh
total 8.0K
-rw-r--r-- 1 10568 10568 26 May 31  2024 robots.txt
-rw-r--r-- 1 root  root  26 May 31  2024 robots2.txt
```

**Comment by jonathanspw** [comment]
@syu5488 would you like to submit a PR for this or want us to tackle it?
