### ISSUE TITLE
Add Vault and 32bit repo info

### ISSUE THREAD

**Issue by srbala** [AlmaLinux/wiki#75]
It would be nice to add information about Vault and 32Bit repo and usage info to repo link would be great.

https://wiki.almalinux.org/repos/

**Comment by andrewlukoshko** [comment]
@sboldyreva

**Comment by sboldyreva** [comment]
Info about Vault and 32Bit added

**Comment by srbala** [comment]
@sboldyreva thank you

cross reference https://github.com/AlmaLinux/wiki/commit/235e190fd45aceb4a2a4c1ecb284608b6b0c6de0#diff-4f41165783cde3827079205f3721b2fa207917c17330cfb4685ad902ebea5ba6L15
