### ISSUE TITLE
touch repo No effect

### ISSUE THREAD

**Issue by agoni03** [AlmaLinux/wiki#8]
sudo tee /etc/yum.repos.d/mariadb.repo<<EOF
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.5/rhel8-amd64
module_hotfixes=1
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF

dnf clean all 
dnf makecache
dnf install MariaDB-server

not match

**Comment by srbala** [comment]
@agoni03 Is this a question or issue?

it looks you are attempt to install RHEL specific packages into AlmaLinux? https://yum.mariadb.org/10.5/ it seems packages are tailered to specific release.

you may need a EPL compatable packages to install with AlmaLinux

**Comment by srbala** [comment]
Please ask your questions in chat/forum or IRC channels

Team, this is not an issue

**Comment by jaboutboul** [comment]
closed as this is not the right place for this. please ask on https://forums.almalinux.org or https://chat.almalinux.org
